export const menuItemsMock = [
  {
    id: 1,
    category: 'Combos',
    name: 'Combo 1',
    description: 'Pasto, pollo, chorizo, longaniza, macisa, lengua, asada, ojo, ubre, mushque, pastor con chicharrón',
    price: 25.0,
    brief:'2 tacos + 1 soda',
    image:'https://drive.google.com/uc?export=view&id=1gCeeTcU7YD7zdSUy2tUwFtza6sdI8yZp',
  },
  {
    id: 2,
    category: 'Combos',
    name: 'Combo 2',
    description: 'Pasto, pollo, chorizo, longaniza, macisa, lengua, asada, ojo, ubre, mushque, pastor con chicharrón',
    price: 45.0,
    brief:'4 tacos + 1 soda',
    image:'https://drive.google.com/uc?export=view&id=1j_RRS6IbQD8PB2q2H-rUzpECr4m3iAuf',
  },
  {
    id: 3,
    category: 'Combos',
    name: 'Combo 3',
    description: 'Pasto, pollo, chorizo, longaniza, macisa, lengua, asada, ojo, ubre, mushque, pastor con chicharrón',
    price: 27.0,
    brief:'2 gringas + 1 soda',
    image:'https://drive.google.com/uc?export=view&id=1lOQFi_tAr_B56dN_Mh2XhZ9AFQBjeHAf',
  },
  {
    id: 4,
    category: 'Combos',
    name: 'Combo 4',
    description: 'Pasto, pollo, chorizo, longaniza, macisa, lengua, asada, ojo, ubre, mushque, pastor con chicharrón',
    price: 45.0,
    brief:'4 gringas + 1 soda',
    image:'https://drive.google.com/uc?export=view&id=1THxkVD3v6tdRgZaW3dnMMVXTEDT5JPrL',
  },
  {
    id: 5,
    category: 'Combos',
    name: 'Combo 5',
    description: 'Pasto, pollo, chorizo, longaniza, macisa, lengua, asada, ojo, ubre, mushque, pastor con chicharrón',
    price: 140.0,
    brief:'6 tacos + 6 gringas + 3 sodas',
    image:'https://drive.google.com/uc?export=view&id=19zgsleKh9olm9e2-FuO_RrwXV2kejKnf',
  },
  {
    id: 6,
    category: 'Combos',
    name: 'Combo 6',
    description: 'Pasto, pollo, chorizo, longaniza, macisa, lengua, asada, ojo, ubre, mushque, pastor con chicharrón',
    price: 30.0,
    brief:'1 chapina + 1 soda',
    image:'https://drive.google.com/uc?export=view&id=1Qc36Kv8sslkKSjCE0QqYXJcV59-bIDSb',
  },
  {
    id: 7,
    category: 'Individuales',
    name: 'Taco',
    description: 'Pasto, pollo, chorizo, longaniza, macisa, lengua, asada, ojo, ubre, mushque, pastor con chicharrón',
    price: 30.0,
    brief:'1 unidad',
    image:'https://drive.google.com/uc?export=view&id=1hvnhMucujXgcutyacjjTro3G3uNYbKYP',
  },
  {
    id: 8,
    category: 'Individuales',
    name: 'Gringa',
    description: 'Pasto, pollo, chorizo, longaniza, macisa, lengua, asada, ojo, ubre, mushque, pastor con chicharrón',
    price: 30.0,
    brief:'1 unidad',
    image:'https://drive.google.com/uc?export=view&id=1lOQFi_tAr_B56dN_Mh2XhZ9AFQBjeHAf',
  },
  {
    id: 9,
    category: 'Individuales',
    name: 'Chapina',
    description: 'Pasto, pollo, chorizo, longaniza, macisa, lengua, asada, ojo, ubre, mushque, pastor con chicharrón',
    price: 30.0,
    brief:'1 unidad',
    image:'https://drive.google.com/uc?export=view&id=1lOQFi_tAr_B56dN_Mh2XhZ9AFQBjeHAf',
  },
  {
    id: 10,
    category: 'Individuales',
    name: 'Soda',
    description: 'en lata: Pepsi, 7Up, Salutaris, etc',
    price: 7.0,
    brief:'1 unidad',
    image:'',
  },
  {
    id: 11,
    category: 'Individuales',
    name: 'Agua pura',
    description: 'en botella',
    price: 5.0,
    brief:'1 unidad',
    image:'',
  },
];
