export const menuItemsMock = [
  {
    id: 1,
    category: 'Combos',
    name: 'Combo 1',
    description: 'Pasto, pollo, chorizo, longaniza, macisa, lengua, asada, ojo, ubre, mushque, pastor con chicharrón',
    price: 25.0,
    brief:'2 tacos + 1 soda',
    image:'',
  },
  {
    id: 2,
    category: 'Combos',
    name: 'Combo 2',
    description: 'Pasto, pollo, chorizo, longaniza, macisa, lengua, asada, ojo, ubre, mushque, pastor con chicharrón',
    price: 45.0,
    brief:'4 tacos + 1 soda',
    image:'',
  },
  {
    id: 3,
    category: 'Combos',
    name: 'Combo 3',
    description: 'Pasto, pollo, chorizo, longaniza, macisa, lengua, asada, ojo, ubre, mushque, pastor con chicharrón',
    price: 27.0,
    brief:'2 gringas + 1 soda',
    image:'',
  },
  {
    id: 4,
    category: 'Combos',
    name: 'Combo 4',
    description: 'Pasto, pollo, chorizo, longaniza, macisa, lengua, asada, ojo, ubre, mushque, pastor con chicharrón',
    price: 45.0,
    brief:'4 gringas + 1 soda',
    image:'',
  },
  {
    id: 5,
    category: 'Combos',
    name: 'Combo 5',
    description: 'Pasto, pollo, chorizo, longaniza, macisa, lengua, asada, ojo, ubre, mushque, pastor con chicharrón',
    price: 140.0,
    brief:'6 tacos + 6 gringas + 3 sodas',
    image:'',
  },
  {
    id: 6,
    category: 'Combos',
    name: 'Combo 6',
    description: 'Pasto, pollo, chorizo, longaniza, macisa, lengua, asada, ojo, ubre, mushque, pastor con chicharrón',
    price: 30.0,
    brief:'1 chapina + 1 soda',
    image:'',
  },
];
