export const menuItemsMock = [
  {
    id: 1,
    category: 'Inventario La Borgoña',
    name: 'Pan baguet',
    description: '',
    price: 8.0,
    brief:'',
    image: '',
  },
  {
    id: 2,
    category: 'Inventario La Borgoña',
    name: 'Gusanito',
    description: '',
    price: 10.0,
    brief:'',
    image: '',
  },
  {
    id: 3,
    category: 'Inventario La Borgoña',
    name: 'Bollo',
    description: '',
    price: 10.0,
    brief:'de leche',
    image: 'https://instagram.fgua5-1.fna.fbcdn.net/v/t51.2885-15/e35/s1080x1080/67136098_2450641661721738_2293550835953114707_n.jpg?_nc_ht=instagram.fgua5-1.fna.fbcdn.net&_nc_cat=106&_nc_ohc=qCyDpyTAlzIAX9-zMIy&_nc_tp=15&oh=57af296c251713b89bba13c30974eedc&oe=5FB58FFB',
  },
  {
    id: 4,
    category: 'Inventario La Borgoña',
    name: 'Bollo',
    description: '',
    price: 20.0,
    brief:'queso crema',
    image: '',
  },
  {
    id: 5,
    category: 'Inventario La Borgoña',
    name: 'Churritos',
    description: '',
    price: 10.0,
    brief:'',
    image: '',
  },
  {
    id: 6,
    category: 'Inventario La Borgoña',
    name: 'Polvorosas',
    description: '',
    price: 16.0,
    brief:'',
    image: '',
  },
  {
    id: 7,
    category: 'Inventario La Borgoña',
    name: 'Baguette',
    description: '',
    price: 10.0,
    brief:'precocido pequeño',
    image: 'https://instagram.fgua5-1.fna.fbcdn.net/v/t51.2885-15/sh0.08/e35/s750x750/101661569_3197960633575574_2821977538457166642_n.jpg?_nc_ht=instagram.fgua5-1.fna.fbcdn.net&_nc_cat=102&_nc_ohc=Ee5zQThyulEAX-S8-MS&_nc_tp=24&oh=4c5fd51f972b51f6f81616d79d544f80&oe=5FB935B6',
  },
  {
    id: 8,
    category: 'Inventario La Borgoña',
    name: 'Palitos',
    description: '',
    price: 10.0,
    brief:'normal',
    image: '',
  },
  {
    id: 9,
    category: 'Inventario La Borgoña',
    name: 'Palito',
    description: '',
    price: 15.0,
    brief:'de queso',
    image: '',
  },
  {
    id: 10,
    category: 'Inventario La Borgoña',
    name: 'Palito',
    description: '',
    price: 10.0,
    brief:'de albahaca',
    image: '',
  },
  {
    id: 11,
    category: 'Inventario La Borgoña',
    name: 'Lenguitas',
    description: '',
    price: 10.0,
    brief:'',
    image: '',
  },
  {
    id: 12,
    category: 'Inventario La Borgoña',
    name: 'Champurrada',
    description: '',
    price: 10.0,
    brief:'clásica',
    image: '',
  },
  {
    id: 13,
    category: 'Inventario La Borgoña',
    name: 'Champurrada',
    description: '',
    price: 19.0,
    brief:'integral',
    image: '',
  },
  {
    id: 14,
    category: 'Inventario La Borgoña',
    name: 'Champurradas',
    description: '',
    price: 19.0,
    brief:'avena',
    image: '',
  },
  {
    id: 15,
    category: 'Inventario La Borgoña',
    name: 'Cobaneritos',
    description: '',
    price: 10.0,
    brief:'',
    image: '',
  },
  {
    id: 16,
    category: 'Inventario La Borgoña',
    name: 'Churros o roscas',
    description: '',
    price: 10.0,
    brief:'',
    image: '',
  },
  {
    id: 17,
    category: 'Inventario La Borgoña',
    name: 'Herrajes',
    description: '',
    price: 15.0,
    brief:'de Tecpán',
    image: '',
  },
  {
    id: 18,
    category: 'Inventario La Borgoña',
    name: 'Rosca Catalana',
    description: '',
    price: 15.0,
    brief:'',
    image: '',
  },
  {
    id: 19,
    category: 'Inventario La Borgoña',
    name: 'Alfajores',
    description: '',
    price: 20.0,
    brief:'',
    image: '',
  },
  {
    id: 20,
    category: 'Inventario La Borgoña',
    name: 'Polvorosas',
    description: '',
    price: 10.0,
    brief:'',
    image: '',
  },
  {
    id: 21,
    category: 'Inventario La Borgoña',
    name: 'Magdalena',
    description: '',
    price: 30.0,
    brief:'glaseada',
    image: '',
  },
  {
    id: 22,
    category: 'Inventario La Borgoña',
    name: 'Magdalena',
    description: '',
    price: 35.0,
    brief:'glase cremoso',
    image: '',
  },
  {
    id: 23,
    category: 'Inventario La Borgoña',
    name: 'Magdalena mix',
    description: '',
    price: 30.0,
    brief:'(vainilla y chocolate)',
    image: '',
  },
  {
    id: 24,
    category: 'Inventario La Borgoña',
    name: 'Quesadillas de arroz',
    description: '',
    price: 25.0,
    brief:'',
    image: '',
  },
  {
    id: 25,
    category: 'Inventario La Borgoña',
    name: 'Brownies',
    description: '',
    price: 45.0,
    brief:'',
    image: '',
  },
  {
    id: 26,
    category: 'Inventario La Borgoña',
    name: 'Brownies',
    description: '',
    price: 50.0,
    brief:'con nuez',
    image: '',
  },
  {
    id: 27,
    category: 'Inventario La Borgoña',
    name: 'Cinnamon rolls',
    description: '',
    price: 20.0,
    brief:'',
    image: '',
  },
  {
    id: 28,
    category: 'Inventario La Borgoña',
    name: 'Muffins',
    description: '',
    price: 20.0,
    brief:'de chocolate y chispas',
    image: '',
  },
  {
    id: 29,
    category: 'Inventario La Borgoña',
    name: 'Muffins',
    description: '',
    price: 20.0,
    brief:'de zanahoria y nuez)',
    image: '',
  },
  {
    id: 30,
    category: 'Inventario La Borgoña',
    name: 'Tamales y pachez',
    description: '',
    price: 10.0,
    brief:'',
    image: '',
  },
  {
    id: 31,
    category: 'Inventario La Borgoña',
    name: 'Tostadas',
    description: '',
    price: 17.0,
    brief:'',
    image: '',
  },
  {
    id: 32,
    category: 'Inventario La Borgoña',
    name: 'Tacos para rellenar',
    description: 'Con masa de maíz o de arroz',
    price: 19.0,
    brief:'',
    image: '',
  },
  {
    id: 33,
    category: 'Inventario La Borgoña',
    name: 'Nachos',
    description: 'Con masa de maíz o de arroz',
    price: 17.0,
    brief:'(natural y barbacoa)',
    image: '',
  },
  {
    id: 34,
    category: 'Inventario La Borgoña',
    name: 'Tortillas harina',
    description: '',
    price: 10.0,
    brief:'',
    image: '',
  },
  {
    id: 35,
    category: 'Inventario La Borgoña',
    name: 'Miel 100% pura',
    description: '',
    price: 55.0,
    brief:'',
    image: '',
  },
  {
    id: 36,
    category: 'Inventario La Borgoña',
    name: 'Plataninas sabores',
    description: '',
    price: 8.00,
    brief:'',
    image: '',
  },
  {
    id: 37,
    category: 'Inventario La Borgoña',
    name: 'Chocolate Mixqueño',
    description: '',
    price: 30.0,
    brief:'',
    image: '',
  },
  {
    id: 38,
    category: 'Inventario La Borgoña',
    name: 'Queso fresco',
    description: '',
    price: 14.0,
    brief:'',
    image: '',
  },
  {
    id: 39,
    category: 'Inventario La Borgoña',
    name: 'Crema pura',
    description: '',
    price: 14.0,
    brief:'',
    image: '',
  },
  {
    id: 40,
    category: 'Inventario La Borgoña',
    name: 'Queso panela',
    description: '',
    price: 35.0,
    brief:'',
    image: '',
  },
  {
    id: 41,
    category: 'Inventario La Borgoña',
    name: 'Queso capas',
    description: 'normal, chile pimiento, jalapeño y loroco si es temporada',
    price: 45.0,
    brief:'',
    image: '',
  },
  {
    id: 42,
    category: 'Inventario La Borgoña',
    name: 'Requesón',
    description: '',
    price: 14.0,
    brief:'',
    image: '',
  },
  {
    id: 43,
    category: 'Inventario La Borgoña',
    name: 'Jugo de naranja natural',
    description: '',
    price: 28.0,
    brief:'',
    image: '',
  },
];
